# The URL the site will be built for
base_url = "https://goyo.hahwul.com"
title = "Goyo"
description = "Goyo is Theme"

build_search_index = true
default_language = "en"
generate_feeds = true
generate_sitemap = true

[markdown]
highlight_code = true
bottom_footnotes = true
highlight_theme = "ayu-mirage"

[languages.ko]
generate_feeds = true
build_search_index = true

[extra]
logo_text = "Goyo"
logo_image_path = "images/goyo.png"
footer_html = "Powered by <a href='https://www.getzola.org'>Zola</a> and <a href='https://github.com/hahwul/goyo'>Goyo</a>"
default_thumbnail = "images/default_thumbnail.jpg"
twitter_site = "@hahwul"
twitter_creator = "@hahwul"
default_colorset = "dark"
gtag = ""
sidebar_expand_depth = 1
disable_root_sidebar_hide = false


nav = [
    { name = "Documents", url = "/introduction", type = "url", icon = "fa-solid fa-book" },
    { name = "GitHub", url = "https://github.com/hahwul/goyo", type = "url", icon = "fa-brands fa-github" },
    { name = "Links", type = "dropdown", icon = "fa-solid fa-link", members = [
        { name = "Creator Blog", url = "https://www.hahwul.com", type = "url", icon = "fa-solid fa-fire-flame-curved" },
        { name = "Zola Offical", url = "https://getzola.org", type = "url", icon = "fa-solid fa-z" },
    ] },
]
